### PR TITLE
Doc73 patch 1

### PR DESCRIPTION
**Pull request by Doc73**
Please, consider reverting the latin translation of ```origin``` field.
However, I still have many doubts, so wait to do the merging. I'm open to suggestions.

### CODE REVIEW

**Comment by maieul** [comment]
I don't understand your PULL request. Please restart from master.

**Comment by Doc73** [comment]
Unfortunately, I'm not familiar with the github interface.
BTW, my suggestion is to write
```origin = {{origo}{orig\adddotspace}},```
instead of
```origin = {{originem ducens ex}{orig\adddotspace duc\adddotspace ex}},```

**Comment by maieul** [comment]
oki, but it is very difficult for me to do manually report. 

So it is ok for now, but next time, please do it proprely. As you made a mistake in your first PR, you should.

1. Delete your fork
2. For again the project
3. Create a branch in your project
4. Do the PR

I won't release now, becuase I guess you will have more change in the future...

**Comment by Doc73** [comment]
Done!
Let me think about what the best solutions are. I accept suggestions!

**Pull request closed without merging**
