### PR TITLE
Add latin locale

### PR DESCRIPTION
**Pull request by Doc73**
Dear Maieul, you could, if you want, add latin locale to your package.
Many thanks in advance,
Domenico

### CODE REVIEW

**Comment by maieul** [comment]
Dear Domenico,

I have squashed yours commit and merged them, then released to CTAN.

Thanks a lot.

Please next time, don't commit directly to your master, but use a branch instead... you will lost the synchronisation with the upstream repository.

**Comment by Doc73** [comment]
Ok!

**Comment by Doc73** [comment]
@maieul 
There is only a difficult: this localization file assumes that latin is supported by polyglossia, which it is not.
Could you test in your system, which is clean, if it works before uploading the new package??

**Comment by maieul** [comment]
Sorry, I have already send it... I guess you have tested :(

So... I don't know... I have not a lot of time to consecrate to latex...

**Comment by Doc73** [comment]
I have tested the file and It was working, but there are some issues, that I noticed later

**Comment by maieul** [comment]
Well, You did a typo in the declaration of the language. But now, I have tested and correct it in 1cc6f36.

So if there are any problem regarding latin support in polyglossia, that does not concern this package, but polyglossia and you should ask to polyglossia team.

**Comment by Doc73** [comment]
Yes! I found the problem!
In ```biblatex``` we don't have to load the option ```language=italian``` (or other modern language).
BTW, for the program to work, you need to have a file ```latin.lbx```: I have it and a long time ago I promised myself to offer it to the maintainers of ```polyglossia```, but I never had time to perfect and complete it.

**Comment by maieul** [comment]
I am not sur to understand. I guess biblatex use the local langue name. But of course, if in italian books you want to use latin abbreviation, it is better to overwrite language string.

Or maybe you could use an hook in biblatex in order to switch to latin when you define manuscripts (I guess there are some hooks in biblatex to be called at the beginning of the entry)

**Comment by Doc73** [comment]
Sorry! I was wrong!
I meant that biblatex does not support Latin, but that I created a file for latin, which however is still incomplete

**Comment by maieul** [comment]
Oh... oki. So that is a problem of biblatex, not mine :)

**Comment by Doc73** [comment]
No, it's mine! I have to complete the ```latin.lbx```! :smile:

**Comment by wujastyk** [comment]
I wonder if "jon" finished his [latin.lbx project](https://tex.stackexchange.com/questions/110951/latin-lbx-for-biblatex). Or "[Doc73](https://github.com/plk/biblatex/issues/1240)"?

**Comment by Doc73** [comment]
@wujastyk 
No, I'm not "jon" and, and until now Latin is not supported by biblatex

**Pull request closed without merging**
